/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package View;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import static java.lang.Double.parseDouble;
import modeldatabase.Connector;
import model.ModelMovie;
import Controller.controller;
/**
 *
 * @author Win7
 */
public class MovieView extends javax.swing.JFrame {
    static Connector DB;
    controller movie;
    
    /** Creates new form MovieView
     * @param DB */
    public MovieView(Connector DB) {
        initComponents();
        MovieView.DB = DB;
        this.movie = new controller(new ModelMovie(DB));
        DefaultTableModel model = (DefaultTableModel)this.tbl_movie.getModel();
        Object[] row = new Object[5];
        model.setRowCount(0);
        
        for (int i = 0; movie.index()[i][0] != null; i++) {
            row[0] = movie.index()[i][0];
            row[1] = movie.index()[i][1];
            row[2] = movie.index()[i][2];
            row[3] = movie.index()[i][3];
            row[4] = movie.index()[i][4];
            model.addRow(row);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_movie = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tx_judul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tx_alur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tx_penokohan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tx_akting = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_movie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Judul", "Alur", "Penokohan", "Akting", "Nilai"
            }
        ));
        tbl_movie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_movieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_movie);

        jLabel1.setText("Judul");

        jLabel2.setText("Alur");

        jLabel3.setText("Penokohan");

        jLabel4.setText("Akting");

        tx_akting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_aktingActionPerformed(evt);
            }
        });

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(54, 54, 54)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(tx_judul)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(tx_alur)
                    .add(tx_penokohan)
                    .add(tx_akting, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btn_clear, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btn_delete, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btn_update, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btn_tambah, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tx_judul, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tx_alur, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tx_penokohan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tx_akting, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37)
                .add(btn_tambah)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btn_update)
                .add(11, 11, 11)
                .add(btn_delete)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btn_clear)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
         try{
            String title = tx_title.getText();
            double plot = parseDouble(tx_plot.getText());
            double character= parseDouble(tx_character.getText());
            double acting = parseDouble(tx_acting.getText());

            movie.simpan(title, plot, character, acting);
        } catch(NumberFormatException err){
            JOptionPane.showMessageDialog(null,"Pease Input All Column");
        }
        
        DefaultTableModel model = (DefaultTableModel)this.tbl_movie.getModel();
        Object[] row = new Object[5];
        model.setRowCount(0);
        for (int i = 0; movie.index()[i][0] != null; i++) {
            row[0] = movie.index()[i][0];
            row[1] = movie.index()[i][1];
            row[2] = movie.index()[i][2];
            row[3] = movie.index()[i][3];
            row[4] = movie.index()[i][4];
            model.addRow(row);
        }
        this.tx_title.setText("");
        this.tx_plot.setText("");
        this.tx_character.setText("");
        this.tx_acting.setText("");
    }//GEN-LAST:event_btn_tambahActionPerformed


    
    private void tx_actingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_aktingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_aktingActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        try{
            String title = tx_title.getText();
            double plot = parseDouble(tx_plot.getText());
            double character = parseDouble(tx_character.getText());
            double acting = parseDouble(tx_acting.getText());

            movie.update(title, plot, character, acting);
            
        }catch(NumberFormatException err){
            JOptionPane.showMessageDialog(null,"Mohon isi Semua Kolom");
        }
        DefaultTableModel model = (DefaultTableModel)this.tbl_movie.getModel();
        Object[] row = new Object[5];
        model.setRowCount(0);
        for (int i = 0; movie.index()[i][0] != null; i++) {
            row[0] = movie.index()[i][0];
            row[1] = movie.index()[i][1];
            row[2] = movie.index()[i][2];
            row[3] = movie.index()[i][3];
            row[4] = movie.index()[i][4];
            model.addRow(row);
        }
        this.tx_title.setText("");
        this.tx_plot.setText("");
        this.tx_character.setText("");
        this.tx_acting.setText("");
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        try{
            String title = tx_title.getText();
            movie.delete(title);
        } catch(Exception err){
            JOptionPane.showMessageDialog(null,"Movie Tidak Ada");
        }
        
        DefaultTableModel model = (DefaultTableModel)this.tbl_movie.getModel();
        Object[] row = new Object[5];
        model.setRowCount(0);
        for (int i = 0; movie.index()[i][0] != null; i++) {
            row[0] = movie.index()[i][0];
            row[1] = movie.index()[i][1];
            row[2] = movie.index()[i][2];
            row[3] = movie.index()[i][3];
            row[4] = movie.index()[i][4];
            model.addRow(row);
        }
        this.tx_title.setText("");
        this.tx_plot.setText("");
        this.tx_character.setText("");
        this.tx_acting.setText("");
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        this.tx_title.setText("");
        this.tx_plot.setText("");
        this.tx_character.setText("");
        this.tx_acting.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void tbl_movieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_movieMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)this.tbl_movie.getModel();
        Object titlee = model.getValueAt(this.tbl_movie.getSelectedRow(), 0);
        Object plott = model.getValueAt(this.tbl_movie.getSelectedRow(), 1);
        Object characterr = model.getValueAt(this.tbl_movie.getSelectedRow(), 2);
        Object actingg = model.getValueAt(this.tbl_movie.getSelectedRow(), 3);

        this.tx_title.setText(titlee.toString());
        this.tx_plot.setText(plott.toString());
        this.tx_character.setText(characterr.toString());
        this.tx_acting.setText(actingg.toString());
    }//GEN-LAST:event_tbl_movieMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MovieView(MovieView.DB).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_movie;
    private javax.swing.JTextField tx_acting;
    private javax.swing.JTextField tx_plot;
    private javax.swing.JTextField tx_title;
    private javax.swing.JTextField tx_character;
    // End of variables declaration//GEN-END:variables

}